language: java
sudo: required
services:
  - docker

before_install:
  - docker build -t sebastiansobolewski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sebastiansobolewski/react-test npm test -- --coverage

after_success:
  - docker build -t sebastiansobolewski/multi-client ./client
  - docker build -t sebastiansobolewski/multi-nginx ./nginx
  - docker build -t sebastiansobolewski/multi-server ./server
  - docker build -t sebastiansobolewski/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sebastiansobolewski/multi-client
  - docker push sebastiansobolewski/multi-nginx
  - docker push sebastiansobolewski/multi-server
  - docker push sebastiansobolewski/multi-worker

